import { useEffect, useState } from "react";
import "./style.css";

const ItemDetail = ({ closeDetail, data }: IItemDetailProps) => {
  const { title, url, description, image } = data || {};

  const [screenWidth, setScreenWidth] = useState(window.innerWidth);

  const handleWindowSizeChange = () => setScreenWidth(window.innerWidth);

  useEffect(() => {
    window.addEventListener("resize", handleWindowSizeChange);
    return () => {
      window.removeEventListener("resize", handleWindowSizeChange);
    };
  }, []);

  const mobileProps = screenWidth < 681 ? { className: "result-layer" } : {};

  return (
    <div {...mobileProps} onClick={closeDetail}>
      <div className="item-detail">
        {image ? (
          <img src={image} alt="A random image generated by fakerjs" />
        ) : (
          <span></span>
        )}
        <cite>{url}</cite>
        <h2>{title}</h2>
        <p>{description}</p>
      </div>
    </div>
  );
};

export default ItemDetail;
