import { faker } from "@faker-js/faker";

const Avatar = () => {
  const avatar = faker.image.avatar();

  return (
    <div className="avatar">
      <img src={avatar} alt="A random avatar image generated by Faker JS" />
    </div>
  );
};

export default Avatar;
